package com.mycompany.app;

import org.testng.annotations.Test;
import org.testng.annotations.DataProvider;
//This is Basic Data Provider example generated by default by TestNG
public class DataProviderBasic {
  @Test(dataProvider = "dp") //dataProvider is attribute that we use with @Test annotation and mention name of dataprovider method(by default its dp)
  public void f(Integer n, String s) {//This is the method that executes with different values(from dp method) everytime 
  } // Here by default parameters are string and integer which we can change

  
  /* This is by default generated method
  @DataProvider
  public Object[][] dp() {//This is dp method, it has return type as multidimensional object
    return new Object[][] {
      new Object[] { 1, "a" }, //different objects/values, first being integer and second being string
      new Object[] { 2, "b" },
    };
    */
//we can also write same thing like this without writing new Object[][]
  @DataProvider
  public Object[][] dp() {//This is dp method, it has return type as multidimensional object
    return new Object[][] {
      { 1, "a" }, //different objects/values, first being integer and second being string
      { 2, "b" },
      { 3, "c" },
      { 4, "d" },      
      { 5, "e" },
      { 6, "f" },
      { 7, "g" },
      { 8, "h" },
      { 9, "i" },
    };
  }
}
//execution and output is seen in same sequence in which values are given in data provider